/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        back1 = new com.k33ptoo.components.KButton();
        next = new com.k33ptoo.components.KButton();
        student = new com.k33ptoo.components.KButton();
        teacher = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back1.setForeground(new java.awt.Color(0, 0, 0));
        back1.setText("BACK");
        back1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back1.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        back1.setkEndColor(new java.awt.Color(51, 51, 255));
        back1.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        back1.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        back1.setkSelectedColor(new java.awt.Color(51, 51, 255));
        back1.setkStartColor(new java.awt.Color(255, 255, 255));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 110, -1));

        next.setForeground(new java.awt.Color(0, 0, 0));
        next.setText("NEXT");
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        next.setkEndColor(new java.awt.Color(51, 51, 255));
        next.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        next.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        next.setkSelectedColor(new java.awt.Color(51, 51, 255));
        next.setkStartColor(new java.awt.Color(255, 255, 255));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        kGradientPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 110, -1));

        student.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        student.setText("STUDENT");
        student.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        student.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        student.setkForeGround(new java.awt.Color(0, 0, 0));
        student.setkHoverColor(new java.awt.Color(153, 153, 255));
        student.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        student.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        student.setkHoverStartColor(new java.awt.Color(255, 255, 153));
        student.setkSelectedColor(new java.awt.Color(255, 255, 255));
        student.setkStartColor(new java.awt.Color(255, 255, 0));
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        kGradientPanel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 260, 130));

        teacher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        teacher.setForeground(new java.awt.Color(51, 51, 51));
        teacher.setText("TEACHER");
        teacher.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        teacher.setkForeGround(new java.awt.Color(0, 0, 0));
        teacher.setkStartColor(new java.awt.Color(255, 255, 0));
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        kGradientPanel1.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 260, 130));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        // TODO add your handling code here:
        teacher obj = new teacher();
        obj.setVisible(true);
        this.dispose();
                        
    }//GEN-LAST:event_teacherActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
        student obj = new student();
        obj.setVisible(true);
        this.dispose();
                        
    }//GEN-LAST:event_studentActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
      teacher obj = new teacher();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_nextActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        Login obj = new Login();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton back1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton next;
    private com.k33ptoo.components.KButton student;
    private com.k33ptoo.components.KButton teacher;
    // End of variables declaration//GEN-END:variables
}
