/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import controller.Logincontroller;
import controller.loginController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        sign = new com.k33ptoo.components.KButton();
        login = new com.k33ptoo.components.KButton();
        cancelBtn = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        signup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("USERNAME");
        signup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("PASSWORD");
        signup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        userName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        signup.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 292, 47));

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signup.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 292, 44));

        kGradientPanel1.setBackground(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sign.setText("SIGNUP");
        sign.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sign.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        sign.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sign.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        sign.setkSelectedColor(new java.awt.Color(255, 51, 51));
        sign.setkStartColor(new java.awt.Color(0, 0, 255));
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, 100, 40));

        login.setText("LOGIN");
        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setkEndColor(new java.awt.Color(255, 255, 255));
        login.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        login.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        login.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        login.setkSelectedColor(new java.awt.Color(255, 51, 102));
        login.setkStartColor(new java.awt.Color(0, 153, 204));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        kGradientPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 160, -1));

        cancelBtn.setText("CANCEL");
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        cancelBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        cancelBtn.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        cancelBtn.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        cancelBtn.setkSelectedColor(new java.awt.Color(255, 102, 102));
        cancelBtn.setkStartColor(new java.awt.Color(0, 153, 204));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 160, -1));

        signup.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 850, 760));

        kButton1.setText("kButton1");
        signup.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        // TODO add your handling code here:
        signup obj = new signup();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_signActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
         String user = userName.getText();
    String pass = new String(password.getPassword());

    loginController controller = new loginController();
    boolean isValid = controller.validateLogin(user, pass);

    if (isValid) {
        Home obj = new Home();
        obj.setVisible(true);
        this.dispose();       
    } else {
     
        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
    }  
        
        
                 
    }//GEN-LAST:event_loginActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.k33ptoo.components.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton login;
    private javax.swing.JPasswordField password;
    private com.k33ptoo.components.KButton sign;
    private javax.swing.JPanel signup;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
