/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.deleteControl;
import controller.studentController;
import controller.update;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class student extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adddetails = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        grade = new javax.swing.JComboBox<>();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        back = new com.k33ptoo.components.KButton();
        next = new com.k33ptoo.components.KButton();
        cancel = new com.k33ptoo.components.KButton();
        submit1 = new com.k33ptoo.components.KButton();
        update = new com.k33ptoo.components.KButton();
        delete = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adddetails.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        adddetails.setText("Student details");
        jPanel1.add(adddetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Grade");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 257, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 194, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 322, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 393, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Student Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 135, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Contact No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 695, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Birthday");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 614, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 533, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Age");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 460, -1, -1));

        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 276, 33));

        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 307, 276, 37));

        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 382, 276, 33));

        contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 684, 276, 33));

        birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 601, 276, 35));

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 191, 276, 32));

        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 455, 276, 36));

        gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 530, -1, 32));

        grade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "5A", "5B", "5C", "5D" }));
        grade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 249, 62, 30));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("BACK");
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        back.setkEndColor(new java.awt.Color(51, 51, 255));
        back.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        back.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        back.setkSelectedColor(new java.awt.Color(51, 51, 255));
        back.setkStartColor(new java.awt.Color(0, 0, 255));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        kGradientPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 80, 30));

        next.setForeground(new java.awt.Color(0, 0, 0));
        next.setText("NEXT");
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        next.setkEndColor(new java.awt.Color(51, 51, 255));
        next.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        next.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        next.setkSelectedColor(new java.awt.Color(51, 51, 255));
        next.setkStartColor(new java.awt.Color(0, 0, 255));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        kGradientPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 730, 100, 40));

        cancel.setText("CANCEL");
        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setkEndColor(new java.awt.Color(255, 255, 255));
        cancel.setkStartColor(new java.awt.Color(0, 51, 255));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, -1));

        submit1.setText("SUBMIT");
        submit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit1.setkEndColor(new java.awt.Color(255, 255, 255));
        submit1.setkStartColor(new java.awt.Color(0, 51, 255));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        update.setText("UPDATE");
        update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update.setkEndColor(new java.awt.Color(255, 255, 255));
        update.setkStartColor(new java.awt.Color(0, 0, 255));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, -1));

        delete.setText("DELETE");
        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setkEndColor(new java.awt.Color(255, 255, 255));
        delete.setkStartColor(new java.awt.Color(0, 51, 255));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        TeacherTable obj = new TeacherTable();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        StudentTable obj = new StudentTable();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
        String stdID = id.getText();
        String Fname = name.getText();
        String Grade = (String) grade.getSelectedItem();
        String add = address.getText();
        String eml = email.getText();
        String agee = age.getText();
        String gnder = (String) gender.getSelectedItem();
        String btd = birthday.getText();
        String cnt = contact.getText();

        try {
            int id = Integer.parseInt(stdID);
            int agg = Integer.parseInt(agee);

            studentController controller = new studentController();
            controller.stdu(id, Fname, Grade, add, eml, agg, gnder, btd, cnt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
    }            
    }//GEN-LAST:event_submit1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String idText = id.getText(); 
    String emailText = email.getText();
    String addText =address.getText();  
    
    try {
            int id = Integer.parseInt(idText);
            

            update controller = new update();
            controller.update(id, emailText, addText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String idText = id.getText();
      
       try {
            int id = Integer.parseInt(idText);

            deleteControl controller = new deleteControl();
            controller.delete(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
         
    }//GEN-LAST:event_deleteActionPerformed
    }
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adddetails;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private com.k33ptoo.components.KButton back;
    private javax.swing.JTextField birthday;
    private com.k33ptoo.components.KButton cancel;
    private javax.swing.JTextField contact;
    private com.k33ptoo.components.KButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField name;
    private com.k33ptoo.components.KButton next;
    private com.k33ptoo.components.KButton submit1;
    private com.k33ptoo.components.KButton update;
    // End of variables declaration//GEN-END:variables
}
