/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import model.tableLoad;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class TeacherTable extends javax.swing.JFrame {

    /**
     * Creates new form TeacherTable
     */
    public TeacherTable() {
        initComponents();
        loadTableData();
    }
    public void search(){
        String srch = search.getText();
        int ar = Integer.parseInt(srch);
        tableLoad tableLoader = new tableLoad();
         ResultSet resultSet = tableLoader.searchData(ar);
        tableSearch(resultSet);
    }
    
    public void tableSearch(ResultSet result) {
        table2.setModel(DbUtils.resultSetToTableModel(result));
    }
  public void table(ResultSet result) {
        table2.setModel(DbUtils.resultSetToTableModel(result));
    }
private void loadTableData() {
        // Create an instance of tableLoad and fetch data
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.fetchTableData();
        // Call the table method to populate the JTable
        table(resultSet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        next = new com.k33ptoo.components.KButton();
        back1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Teacher_Id", "Teacher_Name", "Address", "Age", "Gender", "Contact.No"
            }
        ));
        jScrollPane1.setViewportView(table2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 1010, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 210, 29));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("TEACHER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next.setForeground(new java.awt.Color(0, 0, 0));
        next.setText("NEXT");
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        next.setkEndColor(new java.awt.Color(51, 51, 255));
        next.setkForeGround(new java.awt.Color(0, 0, 0));
        next.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        next.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        next.setkSelectedColor(new java.awt.Color(51, 51, 255));
        next.setkStartColor(new java.awt.Color(255, 255, 255));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        kGradientPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 110, -1));

        back1.setForeground(new java.awt.Color(0, 0, 0));
        back1.setText("BACK");
        back1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back1.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        back1.setkEndColor(new java.awt.Color(51, 51, 255));
        back1.setkForeGround(new java.awt.Color(0, 0, 0));
        back1.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        back1.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        back1.setkSelectedColor(new java.awt.Color(51, 51, 255));
        back1.setkStartColor(new java.awt.Color(255, 255, 255));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 110, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1090, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        student obj = new student();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        teacher obj = new teacher();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton back1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KButton next;
    private javax.swing.JTextField search;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
