/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controldelete;
import controller.teachercontroller;
import controller.update;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;
import model.update2;

/**
 *
 * @author User
 */
public class teacher extends javax.swing.JFrame {

    /**
     * Creates new form teacher
     */
    public teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is  always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teachername = new javax.swing.JTextField();
        teacherid = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        contactno = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        back = new com.k33ptoo.components.KButton();
        next = new com.k33ptoo.components.KButton();
        delete = new com.k33ptoo.components.KButton();
        cancel = new com.k33ptoo.components.KButton();
        update = new com.k33ptoo.components.KButton();
        submit = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Teacher Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 39, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TEACHER ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 168, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("TEACHER NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 253, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ADDRESS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 333, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("GENDER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 489, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("AGE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CONTACT NO.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 569, -1, -1));

        teachername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(teachername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 307, 33));

        teacherid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(teacherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 307, 33));

        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 403, 310, 33));

        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 322, 310, 33));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "MALE", "FEMALE" }));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 80, 30));

        contactno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 560, 320, 33));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("BACK");
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setkBackGroundColor(new java.awt.Color(51, 0, 255));
        back.setkEndColor(new java.awt.Color(51, 51, 255));
        back.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        back.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        back.setkIndicatorColor(new java.awt.Color(51, 0, 255));
        back.setkSelectedColor(new java.awt.Color(51, 51, 255));
        back.setkStartColor(new java.awt.Color(51, 0, 255));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        kGradientPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 110, -1));

        next.setForeground(new java.awt.Color(0, 0, 0));
        next.setText("NEXT");
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        next.setkEndColor(new java.awt.Color(255, 255, 255));
        next.setkHoverForeGround(new java.awt.Color(255, 51, 102));
        next.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        next.setkSelectedColor(new java.awt.Color(255, 255, 255));
        next.setkStartColor(new java.awt.Color(0, 0, 204));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        kGradientPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 110, -1));

        delete.setText("DELETE");
        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setkEndColor(new java.awt.Color(255, 255, 255));
        delete.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        delete.setkSelectedColor(new java.awt.Color(0, 0, 255));
        delete.setkStartColor(new java.awt.Color(0, 0, 255));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 160, -1));

        cancel.setText("CANCEL");
        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setkEndColor(new java.awt.Color(255, 255, 255));
        cancel.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        cancel.setkSelectedColor(new java.awt.Color(0, 0, 255));
        cancel.setkStartColor(new java.awt.Color(0, 0, 255));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 160, -1));

        update.setText("UPDATE");
        update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update.setkEndColor(new java.awt.Color(255, 255, 255));
        update.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        update.setkSelectedColor(new java.awt.Color(0, 0, 255));
        update.setkStartColor(new java.awt.Color(0, 0, 255));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 160, -1));

        submit.setText("SUBMIT");
        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setkEndColor(new java.awt.Color(255, 255, 255));
        submit.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        submit.setkSelectedColor(new java.awt.Color(0, 0, 255));
        submit.setkStartColor(new java.awt.Color(0, 0, 255));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 160, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


                                        
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Home obj = new Home();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        TeacherTable obj = new TeacherTable();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String idText = teacherid.getText();
      
       try {
            int teacherid = Integer.parseInt(idText);

            controldelete controller = new controldelete();
            controller.delete2(teacherid);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
            
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String idText = teacherid.getText(); 
    String addText = add.getText();
    String conText =contactno.getText();  
    
    try {
            int id = Integer.parseInt(idText);
            

            update2 controller = new update2();
            controller.update(id, addText, conText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
              
        
    }//GEN-LAST:event_updateActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String tId = teacherid.getText();
String tname = teachername.getText();
String addr = add.getText();
String agee = age.getText();
String gnder = (String) gender.getSelectedItem();
String cnt = contactno.getText();


try
{
            int teacherid = Integer.parseInt(tId);
            int age = Integer.parseInt(agee);
            
            
            teachercontroller controller = new teachercontroller();
            controller.teacher(teacherid, tname, addr, age, gnder, cnt);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private com.k33ptoo.components.KButton back;
    private com.k33ptoo.components.KButton cancel;
    private javax.swing.JTextField contactno;
    private com.k33ptoo.components.KButton delete;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton next;
    private com.k33ptoo.components.KButton submit;
    private javax.swing.JTextField teacherid;
    private javax.swing.JTextField teachername;
    private com.k33ptoo.components.KButton update;
    // End of variables declaration//GEN-END:variables

}